name: CI

on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

# fake env variables to bypass env check
env: 
  NEXT_PUBLIC_APP_URL: "https://movies.faithcloud.net"
  NEXT_PUBLIC_TMDB_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MmJhMTBjNDI5OTE0MTU3MzgwOGQyNzEwNGVkMThmYSIsInN1YiI6IjY0ZjVhNTUwMTIxOTdlMDBmZWE5MzdmMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.84b7vWpVEilAbly4RpS01E9tyirHdhSXjcpfmTczI3Q"
  NEXT_PUBLIC_SITE_NAME: "To Play Movies"
  NEXT_PUBLIC_IMAGE_DOMAIN: "https://movies.faithcloud.net"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
